name: Build Docker Project
description: 'Build a Docker image'

runs:

  using: 'composite'
  steps:

    - name: Build with docker
      run: docker build . --file src/main/docker/Dockerfile.jvm --tag academy:$(date +%s)
      shell: ubuntu-latest

    - name: List docker images
      run: docker images
      shell: ubuntu-latest