name: Push Docker Image
description: 'Push a Docker image'

inputs:

  username:
    description: "Path to the Dockerfile"
    required: true
  password:
    description: "Specifies the name for the generated Docker image"
    required: true

runs:

  using: 'composite'
  steps:

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Push Docker image
      run: docker push ${{ ENV.DOCKER_IMAGE_NAME}}
      shell: bash