# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
    - uses: NunoMM/academy/.github/actions/maven_build@main
    - uses: NunoMM/academy/.github/actions/docker_build@main

#    name: Build
#    description: Build application with Maven and create a new Docker image
#    inputs:
#      dockerfile_path:
#        description: "Path to the Dockerfile"
#        required: false
#        default: "Dockerfile"
#    runs:
#      using: composite
#      steps:
#        - run: |
#            echo "Update me with the necessary steps to build the application"
#          shell: bash





